DROP TABLE IF EXISTS Awesome;
CREATE TABLE Awesome(
 Url  VARCHAR(40) primary key,
 Title    VARCHAR(200),
 One VARCHAR(30),
 Two   VARCHAR(30));

INSERT INTO Awesome VALUES('https://i.imgur.com/YduxW6p.jpg', 'Frozen Castle', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/uHDcGHG.jpg', 'Behind the scenes: A Hershey''s ad', 'awesome', 'creativity');
INSERT INTO Awesome VALUES('https://i.imgur.com/mFhKyzh.jpg', 'So true', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/K9NW9af.gif', 'I too appreciate when my server doesn''t hover right over me to refill my drink.', 'awesome', 'creativity');
INSERT INTO Awesome VALUES('https://i.imgur.com/gfjEDAV.jpg', 'Lake Allatoona', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/wZZSTCw.jpg', 'Smelly cat dump', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/q6TsgqX.jpg', 'Dump', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/MQmVbFa.gif', 'Afraid of heights? ', 'awesome', 'creativity');
INSERT INTO Awesome VALUES('https://i.imgur.com/D4gAKdj.jpg', 'How conspiracy theorists sound.', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/bKKLWip.jpg', 'BoJack Horseman', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/l4OBVvT.jpg', 'Amethyst geode with calcite looks like a nuclear explosion', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/eXmshEt.jpg', 'aw yiss', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/JJOQFhZ.jpg', 'Yeah... High five!', 'awesome', 'creativity');
INSERT INTO Awesome VALUES('https://i.imgur.com/rX64KvP.jpg', 'Angry mountain... Content trees', 'awesome', 'creativity');
INSERT INTO Awesome VALUES('https://i.imgur.com/9F0Ql3g.mp4', 'Swan feeding the koi', 'awesome', 'aww');
INSERT INTO Awesome VALUES('https://i.imgur.com/MWmpdGk.jpg', 'Round Bear', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/FA8z3Km.jpg', 'Testing the effects of sound-waves on water', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/yKfJIuK.jpg', 'Pretty pictures of unstirred paint', 'awesome', 'creativity');
INSERT INTO Awesome VALUES('https://i.imgur.com/liloSfp.jpg', 'River table grain reveal', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/t10qT8Q.jpg', 'This guy was the actual mayor during 9/11', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/FdXpprz.jpg', 'I''m actually three hundred years old', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/Dx9m2oN.jpg', 'Bicycle wars', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/3aBbC94.jpg', 'Do you even lift', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/6iQjTbU.mp4', 'Dog reunited with her family after Hurricane Maria', 'awesome', 'aww');
INSERT INTO Awesome VALUES('https://i.imgur.com/fnckb4O.jpg', 'Wiggly Jiggly', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/E0wp0lk.jpg', 'On', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/65l5g6a.jpg', 'Mehh that looked pretty la... WTF HOLY SH*T.', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/fKQ8nAc.jpg', 'Awesome Moana and Te Fiti Cosplay', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/gVOasqG.jpg', 'If those ducks can be civilized so can you. Be like a duck.', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/3hJ5lc4.jpg', 'Well Damn!', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/OpTXqDJ.jpg', 'Mall Santa Uses Sign Language To Communicate With A Young Child', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/xfYsel8.mp4', 'In-flight entertainment', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/cjAXqAo.gif', 'The goodest boy gets the bestest treats', 'awesome', 'dog');
INSERT INTO Awesome VALUES('https://i.imgur.com/efpR4gI.jpg', 'I did my first cut out today!', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/Dql8HTs.jpg', 'Thug life', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/qnrWp1x.jpg', 'We drew a picture together!', 'awesome', 'creativity');
INSERT INTO Awesome VALUES('http://i.imgur.com/nGaghGdh.gif', 'Police helping a cat cross the road.', 'awesome', 'aww');
INSERT INTO Awesome VALUES('https://i.imgur.com/kMHwRJX.jpg', 'Incredible', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/zxMOCEE.jpg', 'When your hungry', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/rkbkXrN.jpg', 'Cute.. Wholesome.. Animals - GIF Collection 2 (Turn on WIFI)', 'awesome', 'aww');
INSERT INTO Awesome VALUES('https://i.imgur.com/eGFv7a1.jpg', 'Teenage Mutant Ninja Turtles (1990) Will Always Be a Classic. Please Enjoy Some Awesome Movie Posters.. Behind the Scenes.. And Promotional Pictures.', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/ki5OV3U.jpg', 'Thor’s Well', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/DK4yhN7.jpg', 'In 1908.. A German Tradesman Took All Sorts of Pictures of Factories in Yokohama.. Japan. These Are My Favorites of Those Pictures. Enjoy!', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/mK79vSb.jpg', 'Tasty PSA', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/bGUJ0Xn.jpg', 'Three year old Texas boy without hands or legs is one fantastic big brother.', 'awesome', 'aww');
INSERT INTO Awesome VALUES('https://i.imgur.com/AGYKihX.jpg', 'Giant Chicken Tenders In Hawaii Right Now', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/L7mbKLV.mp4', 'Cat plays fetch.', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/T6cLxtA.jpg', 'Haha', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/3HaACaH.jpg', 'Wind is strong in this one!', 'awesome', 'funny');
INSERT INTO Awesome VALUES('http://i.imgur.com/uUYoVs2h.gif', 'Novascope', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/koIQdc5.jpg', 'Fact', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/YSH61xr.jpg', 'I don''t know why but I love it.', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/MER6AJK.jpg', 'MRW I realize it''s almost summer.', 'awesome', 'funny');
INSERT INTO Awesome VALUES('https://i.imgur.com/Cgy9Q6L.jpg', 'Fetch Level... Golden Retriever', 'awesome', 'aww');
INSERT INTO Awesome VALUES('https://i.imgur.com/oO7NjMN.jpg', 'Flash mob? Nope.. just hot.', 'awesome', 'creativity');
INSERT INTO Awesome VALUES('https://i.imgur.com/cyloPTX.jpg', 'Heavy Metal.', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/i16uymG.jpg', 'Gadget wants your soul', 'awesome', 'None');
INSERT INTO Awesome VALUES('https://i.imgur.com/se3hfx7.jpg', 'It''s all in the dose', 'awesome', 'creativity');
INSERT INTO Awesome VALUES('https://i.imgur.com/se3YtVM.jpg', 'Battlebots 2018 - Meet The Robots ', 'awesome', 'None');
INSERT INTO Awesome VALUES('http://i.imgur.com/PvtIq75h.gif', 'One foot slide.', 'awesome', 'creativity');
