DROP TABLE IF EXISTS Aww;
CREATE TABLE Aww(
 Url  VARCHAR(40) primary key,
 Title    VARCHAR(200),
 One VARCHAR(30),
 Two   VARCHAR(30));

INSERT INTO Aww VALUES('https://i.imgur.com/XyLMQYI.jpg', 'Her ice cream face is the best', 'aww', 'None');
INSERT INTO Aww VALUES('http://i.imgur.com/byk7kV9h.gif', 'Day 45.. still no foxes in the hen house. ', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/Krs0Y8B.jpg', 'Nahhh I don''t want the ball that bad', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/79KfVLh.jpg', 'Happy Boy.', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/otanQqN.jpg', 'Wiggle wiggle wiggle', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/Ik5JwwI.jpg', 'Cat at the Playground', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/WbSRuMF.jpg', 'Fluffy boi', 'aww', 'dog');
INSERT INTO Aww VALUES('https://i.imgur.com/F35iFde.jpg', 'Pupper Paisley''s first snow day', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/m9SxCrS.jpg', 'Puppy sneaks under fence to play with his buddy', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/gNbwBD4.jpg', 'Don''t Wait for It..', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/4iIjNh3.jpg', 'Rub a dub dub', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/9F0Ql3g.mp4', 'Swan feeding the koi', 'aww', 'awesome');
INSERT INTO Aww VALUES('https://i.imgur.com/pU5BGiQ.jpg', 'Wait for it..', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/YSH61xr.jpg', 'I don''t know why but I love it.', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/UwxTGO3.jpg', 'Before today I had never seen a bloodhound puppy and felt the need to share', 'aww', 'None');
INSERT INTO Aww VALUES('http://i.imgur.com/NaQEU6Ch.gif', '''Have you finished with that?''', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/X6Ckc7m.jpg', 'Help.. please.', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/owXWMWG.jpg', 'This is my favorite picture of Gus', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/fGderug.mp4', 'Dog had surgery yesterday and hasn''t been able to figure out how to sleep while while wearing a cone. ', 'aww', 'dog');
INSERT INTO Aww VALUES('https://i.imgur.com/NKCMwY8.jpg', 'Corgi of the day (Day 143) Everyone meet Cinnamon!', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/anfaIcX.jpg', 'Update on the new kitten', 'aww', 'None');
INSERT INTO Aww VALUES('http://i.imgur.com/0n6dDOgh.gif', 'Please love me...', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/K5Yte1T.jpg', 'Don''t worry... I got you little bro', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/TwjgmUh.jpg', 'Need some reassurance.', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/zHneNc0.jpg', 'A delectable array of meme morsels', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/ufuZlBr.jpg', 'New Toy Box!', 'aww', 'dog');
INSERT INTO Aww VALUES('https://i.imgur.com/OVMPDaI.jpg', 'Andouille has so much to say to me.', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/ekyZ7vc.jpg', 'Imgur.. meet Captain!', 'aww', 'dog');
INSERT INTO Aww VALUES('https://i.imgur.com/Zh45BaQ.jpg', 'Damned if you do.. damned if you don’t.', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/xfYsel8.mp4', 'In-flight entertainment', 'aww', 'awesome');
INSERT INTO Aww VALUES('http://i.imgur.com/nGaghGdh.gif', 'Police helping a cat cross the road.', 'aww', 'awesome');
INSERT INTO Aww VALUES('https://i.imgur.com/bGUJ0Xn.jpg', 'Three year old Texas boy without hands or legs is one fantastic big brother.', 'aww', 'awesome');
INSERT INTO Aww VALUES('https://i.imgur.com/cr3IoQB.jpg', '"They''ll never see my food under this clear plastic bag!"', 'aww', 'dog');
INSERT INTO Aww VALUES('https://i.imgur.com/nQFSjCO.jpg', 'Ickis'' first car ride', 'aww', 'dog');
INSERT INTO Aww VALUES('https://i.imgur.com/yoR53OD.jpg', 'Scary stairs do pup an afraid', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/ZSOwrx7.mp4', '"I killed the tiger and now I''m wearing his head as my trophy."', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/jfuoynn.jpg', 'Charleston Chew', 'aww', 'dog');
INSERT INTO Aww VALUES('https://i.imgur.com/lmmZPCI.mp4', 'Pretty kitty', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/PC8ri0x.gif', 'Just a Corgi in a raincoat hating its life', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/HbzEfww.mp4', 'Sudden attack.', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/UgiHJFP.jpg', 'FEUER FREI', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/e7ELFKN.jpg', 'Fuck off Linda I can handle it.', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/Z1wsPYj.jpg', 'It’s Mulan’s first cake day!', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/9IyOZCg.jpg', 'Vanishing Veggies', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/5rtXe30.jpg', 'wiggle wiggle wiggle wiggle', 'aww', 'funny');
INSERT INTO Aww VALUES('https://i.imgur.com/LBNrCnx.jpg', 'One of a kind.', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/r0T2q8a.jpg', 'Nabi Video', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/pXPLNoh.jpg', 'Is nice doggo', 'aww', 'dog');
INSERT INTO Aww VALUES('https://i.imgur.com/ThnIAxr.jpg', 'New Friend For Life', 'aww', 'None');
INSERT INTO Aww VALUES('http://i.imgur.com/aY0c7Ysh.gif', 'We heard you called another dog a good boy.', 'aww', 'dog');
INSERT INTO Aww VALUES('https://i.imgur.com/WIRC9qz.jpg', 'Somebody wasn’t a fan of the car wash today.', 'aww', 'dog');
INSERT INTO Aww VALUES('https://i.imgur.com/6iQjTbU.mp4', 'Dog reunited with her family after Hurricane Maria', 'aww', 'awesome');
INSERT INTO Aww VALUES('https://i.imgur.com/Wy0oP0x.jpg', 'smol beans', 'aww', 'creativity');
INSERT INTO Aww VALUES('https://i.imgur.com/Wri06fn.jpg', 'Puppies then and puppies now????????', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/Cgy9Q6L.jpg', 'Fetch Level... Golden Retriever', 'aww', 'awesome');
INSERT INTO Aww VALUES('https://i.imgur.com/1rGBQYP.jpg', 'Dem ears Tho', 'aww', 'None');
INSERT INTO Aww VALUES('https://i.imgur.com/nYQEHoY.jpg', 'Where the good trashcans at?', 'aww', 'None');
INSERT INTO Aww VALUES('http://i.imgur.com/GE7Qdzlh.gif', 'Good boy lends a helping paw to his friend.', 'aww', 'dog');
INSERT INTO Aww VALUES('http://i.imgur.com/YnAHgmYh.gif', '♩ Me..and...my.. shadow ♩', 'aww', 'dog');
INSERT INTO Aww VALUES('http://i.imgur.com/mvikVYhh.gif', 'Newf plays hide-and-seek. He''s not very good.', 'aww', 'funny');
