DROP TABLE IF EXISTS Funny;
CREATE TABLE Funny(
 Url  VARCHAR(40) primary key,
 Title    VARCHAR(200),
 One VARCHAR(30),
 Two   VARCHAR(30));

INSERT INTO Funny VALUES('https://i.imgur.com/U8RLbgH.jpg', 'When you don''t have to bother with those pesky copyright laws...', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/E0wp0lk.jpg', 'On', 'funny', 'awesome');
INSERT INTO Funny VALUES('https://i.imgur.com/6PMRNID.mp4', 'Saving face.', 'funny', 'reaction');
INSERT INTO Funny VALUES('https://i.imgur.com/MwLDqWo.jpg', 'I heard male breasts were acceptable', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/0izyaxr.jpg', 'Phone clearing dump Part 1', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/7vhnJrs.jpg', 'An easy answer', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/CYeR50f.jpg', 'Curb your enthusiasm', 'funny', 'inspiring');
INSERT INTO Funny VALUES('https://i.imgur.com/nbhmaxm.jpg', 'Worst feeling ever!', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/owXWMWG.jpg', 'This is my favorite picture of Gus', 'funny', 'aww');
INSERT INTO Funny VALUES('https://i.imgur.com/wZZSTCw.jpg', 'Smelly cat dump', 'funny', 'awesome');
INSERT INTO Funny VALUES('https://i.imgur.com/m9TCI4S.jpg', 'A Healthy Dose of Ha Ha’s', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/fkAIUWo.jpg', 'Am...am I next?', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/mFhKyzh.jpg', 'So true', 'funny', 'awesome');
INSERT INTO Funny VALUES('https://i.imgur.com/eGrEIpi.jpg', 'I believe I can fly I believe I can touch the sky', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/bfRisf1.jpg', 'Hide ur girlfriends', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/xyYNGo1.jpg', 'Take them off I rather be blind ', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/t10qT8Q.jpg', 'This guy was the actual mayor during 9/11', 'funny', 'awesome');
INSERT INTO Funny VALUES('https://i.imgur.com/RXYHnV5.jpg', 'Savage', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/V5mbO3S.jpg', 'Sweet Memes are made of These - 45th dumperoo', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/k2RVkMh.jpg', 'Relationship Dump (15)', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/qmgFGQa.jpg', 'Fantasy what', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/Lj7mpvf.jpg', 'Streamer thinks his mic is off and wishes his cat goodnight', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/ObV6MZR.jpg', 'Loved this show.', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/v66VXvD.jpg', 'An overview of the Celestials.. Supreme Beings.. and Cosmic Entities', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/uq2dNIT.jpg', 'Double fail fountain', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/DkJnRLs.jpg', 'Go-go-go!', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/PH0l4mh.jpg', 'It’s quite the mouthful!', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/NpbtwZ5.jpg', 'Speed Demons', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/3hJ5lc4.jpg', 'Well Damn!', 'funny', 'awesome');
INSERT INTO Funny VALUES('https://i.imgur.com/qDleso8.jpg', 'Sorry little one.', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/0h120yS.jpg', 'We know what we''re doing', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/bOqgbmg.jpg', 'He married his best friend <3', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/bKKLWip.jpg', 'BoJack Horseman', 'funny', 'awesome');
INSERT INTO Funny VALUES('https://i.imgur.com/TWDkj78.jpg', 'Public dump zone', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/Dql8HTs.jpg', 'Thug life', 'funny', 'awesome');
INSERT INTO Funny VALUES('https://i.imgur.com/LvY78Q0.jpg', 'The Beatles had a great sense of humour', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/LaJI241.jpg', 'Phone Dump', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/JIxHgLD.jpg', 'I never noticed', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/pnKSVUP.jpg', 'Rejection', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/HYZvpYX.jpg', 'Funny Trash Panda', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/5rtXe30.jpg', 'wiggle wiggle wiggle wiggle', 'funny', 'aww');
INSERT INTO Funny VALUES('https://i.imgur.com/NeVXvjr.jpg', 'Wow', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/yGeuVNv.jpg', '"Oh yeah.. let me get that juicy...... no shit no.. no.. get off me"', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/HVD5Tim.jpg', 'If y''all don''t dont at least get a little bit sweaty when cap pulls in that helicopter in winter solider then you''re lying', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/6wqs96u.jpg', 'He couldn’t find love in a cave so...', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/cJmWJER.jpg', 'Post title here', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/Qv9PLfp.jpg', 'Best respons imaginable', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/AGYKihX.jpg', 'Giant Chicken Tenders In Hawaii Right Now', 'funny', 'awesome');
INSERT INTO Funny VALUES('https://i.imgur.com/gsn5qcm.jpg', 'furget me not', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/st5j6mn.jpg', 'kids are so innocent', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/l1jgAHZ.jpg', 'Just a quick reminder for Imgurians.', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/k96TgL9.jpg', 'MRW someone asks if I''m still a Dapper Dan man', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/Tg2wtkF.jpg', 'Dennis Reynolds: Psychopath', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/5r4yMDc.jpg', 'This is a real tweet from Denny’s', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/8b2HyXA.jpg', 'Just thinking of it pains me', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/8iiO2W2.jpg', 'Who want some grapes?', 'funny', 'None');
INSERT INTO Funny VALUES('http://i.imgur.com/mvikVYhh.gif', 'Newf plays hide-and-seek. He''s not very good.', 'funny', 'aww');
INSERT INTO Funny VALUES('https://i.imgur.com/3zEBjSW.jpg', 'First Dump', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/i55zeWW.jpg', 'Hello darkness my old friend', 'funny', 'None');
INSERT INTO Funny VALUES('https://i.imgur.com/ER75TwM.jpg', 'THE REACTION', 'funny', 'reaction');
