DROP TABLE IF EXISTS Gaming;
CREATE TABLE Gaming(
 Url  VARCHAR(40) primary key,
 Title    VARCHAR(200),
 One VARCHAR(30),
 Two   VARCHAR(30));

INSERT INTO Gaming VALUES('http://i.imgur.com/pEk7RiRh.gif', 'He wasn''t hanging around ', 'gaming', 'funny');
INSERT INTO Gaming VALUES('https://i.imgur.com/yJ8qz3B.jpg', 'Hiking around in my alien puzzle adventure game', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/0JzKI6I.jpg', 'Gamers Then vs. Now', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/bQbqr9M.jpg', 'Battlefield 5 release date.. check it out on youtube channel Rey RedOne', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/hvpvPjV.jpg', 'Indian Legend of Zelda', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/hrcJ29h.jpg', 'The Burger King Xbox game were clearly the best advertisement/games ever', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/J8H2mtb.jpg', 'A Chinese Woman Spent 10 Years Living In Internet Cafe', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/96gY9vd.jpg', 'Cities Skylines: Osahra - The Rebel Camp', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/DuZMxJz.jpg', 'Borderlands Style Pyro', 'gaming', 'creativity');
INSERT INTO Gaming VALUES('https://i.imgur.com/VAEVhG5.jpg', 'Ástor Alexander''s posters', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/H7BX1Ci.jpg', 'Is the 7Up ‘Cool Spot’ SNES game the best full-blown     advertisement/game ever?', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/JbuIhlB.jpg', 'A friendly reminder to Steam users.', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/oyAdtYx.jpg', 'Gaming Dump 2.0', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/wZaibFV.jpg', '3D models we made for the game FAR: Lone Sails', 'gaming', 'creativity');
INSERT INTO Gaming VALUES('https://i.imgur.com/2SbQxP3.jpg', 'Alright Thanos.', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/kMnGM4j.jpg', 'God of War III Remastered - 4K High Quality Gameplay Moments', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/4jaFxKI.jpg', 'WHEN PLP SENDS INVITES', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/5LcEQrt.jpg', 'New post  Dedicated to everyone who closed imgur a moment ago!', 'gaming', 'awesome');
INSERT INTO Gaming VALUES('https://i.imgur.com/mHhpnV4.jpg', 'I made a thing... My Recalbox in a box', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/0bXhZtP.jpg', 'The Thief and the Rebel', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/G5X2jOS.jpg', '‘member?', 'gaming', 'funny');
INSERT INTO Gaming VALUES('https://i.imgur.com/qZHnHNG.jpg', 'First Gaming PC Build', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/bKbWG8n.jpg', 'Triggered', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/P7e77fv.jpg', 'Laura and Sombra Beach Day', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/fGzd2mO.jpg', 'Iron Harvest LEGO mech!', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/awyB7TE.gif', 'Dad Jokes with Kratos', 'gaming', 'funny');
INSERT INTO Gaming VALUES('https://i.imgur.com/ZQNQBtB.jpg', 'Maybe now my friends will stop asking me to help them move. (OC)', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/MBNPLnZ.jpg', 'Foliage adds a nice touch (The Pedestrian)', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/XGJDG6l.jpg', 'Pantropy devblog', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/WbzaYAm.jpg', 'Day 84 Lizardmen a Day! You thought I forgot about Halo.', 'gaming', 'None');
INSERT INTO Gaming VALUES('http://i.imgur.com/ZH3fbjuh.gif', 'Gameplay from Last Epoch.. an in development ARPG', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/QKeU19e.jpg', '1998 PlayStation Catalog', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/OU0lwL2.gif', 'big drama show ', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/gWTCsIE.jpg', 'Tropical Burn', 'gaming', 'funny');
INSERT INTO Gaming VALUES('https://i.imgur.com/j0U6GRa.jpg', 'My Custom Tie Intercepter', 'gaming', 'creativity');
INSERT INTO Gaming VALUES('https://i.imgur.com/tXCg6Dz.jpg', 'Combat spell casting', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/YDWtPGK.jpg', 'Expectation - Reality', 'gaming', 'funny');
INSERT INTO Gaming VALUES('https://i.imgur.com/eQn7Ndq.jpg', 'Nurse Joy catching her first Chansey', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/KVZ2Tvd.jpg', 'My clients asked for Pokemon stuff.. so I tried to deliver', 'gaming', 'funny');
INSERT INTO Gaming VALUES('http://i.imgur.com/qv8n2DIh.gif', 'We’re celebrating the release of Fictorum v1.1 the best way we know how.. by destroying a bridge.. again!', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/IG7iUfv.jpg', 'Psyduck Polygon Art', 'gaming', 'creativity');
INSERT INTO Gaming VALUES('https://i.imgur.com/zKz157z.jpg', 'GTA <3', 'gaming', 'awesome');
INSERT INTO Gaming VALUES('https://i.imgur.com/tN8yzTN.jpg', 'One of the oldest .gifs', 'gaming', 'awesome');
INSERT INTO Gaming VALUES('https://i.imgur.com/vXNhf5n.jpg', 'Just decided to open up my hoard of genuine wrestle boys.', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/0cfBd5P.jpg', 'Just another day on the NYC subway (OC)', 'gaming', 'None');
INSERT INTO Gaming VALUES('http://i.imgur.com/tQ70PqSh.gif', 'Blyatoshock!!', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/ja4pWzw.jpg', 'Kingdom Death: Monster.. Sunstalker', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/rkECWea.jpg', 'Majora''s Mask Plushies', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/6TYxrku.jpg', 'Lunch Sketch: R6 Montagne', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/YSH61xr.jpg', 'I don''t know why but I love it.', 'gaming', 'funny');
INSERT INTO Gaming VALUES('https://i.imgur.com/rn4npw8.mp4', 'MUDA MUDA MUDA MUDA!', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/L2xIjJH.jpg', 'Gyarados Pokèglobe I made', 'gaming', 'awesome');
INSERT INTO Gaming VALUES('https://i.imgur.com/pKaEA5W.jpg', 'Mans never hot', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/LUbqblW.jpg', 'Project Ashe Cosplay', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/8RbINIG.jpg', 'The last 24 hours!', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/lxGUrKU.jpg', 'Surrounded', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/Ltc79Vh.jpg', 'Spell Weaving', 'gaming', 'None');
INSERT INTO Gaming VALUES('https://i.imgur.com/lTHVO7Y.gif', 'PlayStation Vita Emulator | Vita3K | Downwell / SwapQuest |', 'gaming', 'None');
INSERT INTO Gaming VALUES('http://i.imgur.com/0YBJLuwh.gif', 'Week 15 progress', 'gaming', 'None');
