DROP TABLE IF EXISTS Reaction;
CREATE TABLE Reaction(
 Url  VARCHAR(40) primary key,
 Title    VARCHAR(200),
 One VARCHAR(30),
 Two   VARCHAR(30));

INSERT INTO Reaction VALUES('https://i.imgur.com/YtcO3GD.mp4', 'Still high after his visit to the vet.', 'reaction', 'aww');
INSERT INTO Reaction VALUES('https://i.imgur.com/nHrseNO.gif', 'Rescued Bobcat Baby Doing a Sneak', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('https://i.imgur.com/DrAL9or.jpg', 'Tinder irl.', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/DpZpKyx.jpg', 'When you see a dog driving a car', 'reaction', 'dog');
INSERT INTO Reaction VALUES('https://i.imgur.com/bdSImCO.mp4', '"I brought you a flower..."', 'reaction', 'dog');
INSERT INTO Reaction VALUES('https://i.imgur.com/6PMRNID.mp4', 'Saving face.', 'reaction', 'funny');
INSERT INTO Reaction VALUES('http://i.imgur.com/ytqNYTSh.gif', 'The littlest yawn.', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('https://i.imgur.com/2O5jWKa.jpg', '"Right here? In my own house?!"', 'reaction', 'dog');
INSERT INTO Reaction VALUES('https://i.imgur.com/zneVLsn.mp4', 'mlem mlem mlem... "alright.. I''ve had enough of this bullshit!"', 'reaction', 'dog');
INSERT INTO Reaction VALUES('http://i.imgur.com/RV5Fiooh.gif', 'Grandpa got the moves.', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('https://i.imgur.com/iXTJBUS.jpg', 'Found this gem in an old venom comic ( funeral pyre)', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/t4P1xPy.jpg', 'The love of a cat.', 'reaction', 'aww');
INSERT INTO Reaction VALUES('https://i.imgur.com/pHomY9b.jpg', '"What have I done..."', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/bRjiqei.jpg', 'Always having fun', 'reaction', 'funny');
INSERT INTO Reaction VALUES('http://i.imgur.com/olYdRGjh.gif', 'Guy climbs into a New York City subway grate.', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/0UXTDqd.jpg', 'GUYS HELP!', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/xk2FTDo.jpg', 'stupid', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/q8ZLHkm.jpg', 'MRW my wife suddenly starts an argument I’ve been preparing for all day', 'reaction', 'None');
INSERT INTO Reaction VALUES('http://i.imgur.com/6lZVU89h.gif', '"Abort! Abort!"', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('https://i.imgur.com/nr3o5L1.jpg', 'Ooh... Is that a free spot? Slowly ... Sloooooowly ... move like a shadow...he''ll never even know', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/iQKpJUu.jpg', 'Another reaction image.', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/YSWjpC6.jpg', 'Good things come to those who wait...', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/AaYoGNS.jpg', 'Upvote reaction.', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/T63ze5X.jpg', 'New reaction gif.', 'reaction', 'None');
INSERT INTO Reaction VALUES('http://i.imgur.com/NaQEU6Ch.gif', '''Have you finished with that?''', 'reaction', 'funny');
INSERT INTO Reaction VALUES('http://i.imgur.com/AaaFLcUh.gif', 'Kitten enjoys chin scritches.', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('https://i.imgur.com/7EkCnT6.jpg', 'MRW someone when someone takes my pic', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/hz45LDx.jpg', 'When it''s the 24th century.. you''ve overcome your choice to be a slave.. and some guy is fronting over your long time friend but you still move like they did.', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/teRgEKm.gif', 'Thanos: Problem Solver.', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('https://i.imgur.com/ThVfWVD.jpg', 'Mrw someone mentions horoscopes', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/jdvx5a4.mp4', '"What is wrong with your face?!"', 'reaction', 'aww');
INSERT INTO Reaction VALUES('https://i.imgur.com/N9qJuq7.jpg', 'Has anyone really been far even as decided to use even go want to do look more like?', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/dzGzoG2.mp4', 'best day ever', 'reaction', 'aww');
INSERT INTO Reaction VALUES('https://i.imgur.com/RWekLCl.jpg', '“Reaction” photos I use constantly pt 2/2.', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/ngoh10S.mp4', '"Did you seriously just touch my neck!?"', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('http://i.imgur.com/d758yqJh.gif', 'When you post your OC at the wrong time of the day.', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('https://i.imgur.com/7bidYdI.mp4', '"ok.. that''s enough!!"', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/sC0WAAL.gif', 'Hot dog!', 'reaction', 'dog');
INSERT INTO Reaction VALUES('https://i.imgur.com/9uLjO3e.jpg', 'The League was so underrated.', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('https://i.imgur.com/dqdLFFx.gif', 'Hair growth time lapse.', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/h0IdNRg.gif', 'Surgical Precision.', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/f18F50e.mp4', 'So comfy.', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('http://i.imgur.com/cfwrqjUh.gif', '"Are you really going to make me wear that again?"', 'reaction', 'dog');
INSERT INTO Reaction VALUES('https://i.imgur.com/9jCHIiy.jpg', 'Don’t make me wear it again Karen ', 'reaction', 'aww');
INSERT INTO Reaction VALUES('http://i.imgur.com/7vXLJ9Bh.gif', 'How I like to imagine Reddit bans go down..', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/HbzEfww.mp4', 'Sudden attack.', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/LIE7kMB.jpg', 'For Reaction Gif Purposes ', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/2vSel04.mp4', '"this is my piggy!!!"', 'reaction', 'dog');
INSERT INTO Reaction VALUES('http://i.imgur.com/h8cAwLRh.gif', 'MRW my best friend asked me what snack I''d like while we watch the big game', 'reaction', 'gaming');
INSERT INTO Reaction VALUES('https://i.imgur.com/VoaP0YS.jpg', 'Noodles!!', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/L7mbKLV.mp4', 'Cat plays fetch.', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('https://i.imgur.com/xI6XEcO.jpg', '"Currently Africa by Toto is winning for our graduation song and someone doesn''t approve."', 'reaction', 'awesome');
INSERT INTO Reaction VALUES('http://i.imgur.com/bTqH9rBh.gif', '"Strike!"', 'reaction', 'creativity');
INSERT INTO Reaction VALUES('https://i.imgur.com/CSpMmkg.gif', '"My sister''s dog fell asleep on the drive home from the park."', 'reaction', 'aww');
INSERT INTO Reaction VALUES('https://i.imgur.com/VkhSvQl.jpg', 'Don’t fall for Starlord?', 'reaction', 'funny');
INSERT INTO Reaction VALUES('http://i.imgur.com/2oWM2c5h.gif', 'Feels like a Tuesday.', 'reaction', 'creativity');
INSERT INTO Reaction VALUES('https://i.imgur.com/8HQEBQk.jpg', 'Public Service Announcement.', 'reaction', 'funny');
INSERT INTO Reaction VALUES('https://i.imgur.com/c1D13hI.jpg', 'MRW scrolling through random.. I see a recent post from user sub', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/co8b3l7.gif', 'MRW I see that a Russian oligarch funneled money to Trump''s lawyer and think joining an Imgur conversation would be a good idea~', 'reaction', 'None');
INSERT INTO Reaction VALUES('https://i.imgur.com/SMM4DhO.gif', 'Launching from an Aircraft Carrier', 'reaction', 'awesome');
